import {
  BarChart3,
  Brain,
  Building2,
  Cloud,
  Code2,
  Compass,
  Cpu,
  Database,
  Eye,
  Factory,
  Globe,
  GraduationCap,
  Handshake,
  HeartPulse,
  Landmark,
  Layers,
  Lightbulb,
  Lock,
  Palette,
  Rocket,
  Search,
  Shield,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Target,
  Truck,
  Users,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  code: Code2,
  smartphone: Smartphone,
  brain: Brain,
  cloud: Cloud,
  workflow: Workflow,
  shield: Shield,
  palette: Palette,
  chart: BarChart3,
  database: Database,
  layers: Layers,
  rocket: Rocket,
  sparkles: Sparkles,
  cpu: Cpu,
  globe: Globe,
  lightbulb: Lightbulb,
  users: Users,
  cart: ShoppingCart,
  health: HeartPulse,
  education: GraduationCap,
  finance: Landmark,
  truck: Truck,
  factory: Factory,
  building: Building2,
  store: Store,
  search: Search,
  target: Target,
  zap: Zap,
  lock: Lock,
  handshake: Handshake,
  eye: Eye,
  compass: Compass,
  wrench: Wrench,
};

export function Icon({ name, className, strokeWidth = 1.75 }: { name?: unknown; className?: string; strokeWidth?: number }) {
  const Cmp = ICONS[String(name || "")] || Sparkles;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
